### ISSUE TITLE
In memory DB support?

### ISSUE THREAD

**Issue by thomscoder** [mateonunez/asterism#30]
This is not a bug, but a feature proposal and question?

Does asterism support in memory DBs?

For one of my projects, i was thinking to integrate a Search system. My project does all the computation in memory so...

I'd like to integrate Asterism and Lyra. I was thinking to use a in-memory key/val db.

Of course I do not seeing any problem at generating data in an Asterism compliant format (JSON or whatever). I was wondering if there's already support for it or it was in the roadmap, or there won't ever be. 

Or if I'm just tripping and the solution is simpler lol

At the time of writing I'm reading both Asterism and Lyra-Impact to study whichever fits the most.

💯

**Comment by mateonunez** [comment]
Hey @thomscoder, I think you can use native Lyra APIs for it. Indeed, if you plan to integrate a more structured database like: MySQL or Postgres, Asterism can create for you all the Lyra instances automatically and perform searches.

However, more databases will be added in the roadmap, I think in memory databases can be easily implemented by Asterism APIs, so it could be a good argument of discussion.

Let me know how do you want to proceed and if you need help with it.

**Comment by thomscoder** [comment]
Thank youu,

I will look into Lyra native APIs.
Also I'm still architecting... I'm just thinking if going full Golang or getting the help of JS as well.

Thanks for the answer @mateonunez
