### ISSUE TITLE
Implement Asterism fragmentation

### ISSUE THREAD

**Issue by mateonunez** [mateonunez/asterism#52]
Asterism should fragment the big data. Consider the following schema:

```js
const schema = {
  users: {}, // contains 10K of records
  posts: {}, // contains 1M of records
}
```

When an Asterism is generated, there are 2 Lyra instances: one for `users` and another one for `posts`.
The generation of `posts` Lyra instance can be very very slow and can generate a lot of memory issues.

Astersim should fragment that instance into more "little" instances, avoiding memory errors and complex cycles.

```js
const asterism = {
  users: {
    ...lyraInstance
  },
  posts: {
    ...lyraInstance_1,
    ...lyraInstance_2
  }
}
```

**Comment by cogluca** [comment]
Hey Mateo, is it ok if I work on this one?

**Comment by mateonunez** [comment]
Hey @cogluca what's on your mind?
